# Generated by Django 4.2.7 on 2023-11-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='cedula',
            new_name='codigo',
        ),
    ]
